services:
  ollama:
    image: ollama/ollama
    mem_limit: 8g
    memswap_limit: 10g
    environment:
        OLLAMA_NUM_PARALLEL: 1
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
    command: "fastapi dev app/main.py --host 0.0.0.0 --port 80"
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
        - action: rebuild
          path: ./backend/pyproject.toml
    depends_on:
      - ollama
      - vdb
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 80:80
  #   command: "npm run serve --port 80"
  # vdb:
  #   image: chromadb/chroma:1.0.9
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - chroma-data:/data
volumes:
  ollama-data:
  chroma-data: