[project]
name = "rag-fastapi-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=0.6.3",
    "fastapi[standard]>=0.115.12",
    "ollama>=0.4.8",
    "sentence-transformers>=4.1.0",
]
